spring:
  application:
    name: vg-ms-person

  r2dbc:
    # Conexión a bd Person
    url: r2dbc:postgresql://ep-winter-scene-a8apmsq5-pooler.eastus2.azure.neon.tech/PRS_PERSONS?sslmode=require
    username: PRS_PERSONS_owner
    password: npg_q3K6RrBGtyYl

    pool:
      max-size: 20
      min-size: 5
      validation-query: SELECT 1

  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    consumer:
      group-id: person-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: pe.edu.vallegrande.database.model.event
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="WACDQEHOTZLGOU2T" password="faRJjXaJNA8Z/ME4I6tKgQFFlljpbqeJumMTRdene4oaCq//rNmgeDbYqGR4ioiO";
        #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="QPOHIHRZOG4ZZJZ5" password="obWMF0fhB+HKXKUvFz3YvBw2p5qZuubgJN5wZSuz750hjaSD9SLW6fFOcZq4u/lp";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: pe.edu.vallegrande.database.model.event
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config:
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="WACDQEHOTZLGOU2T" password="faRJjXaJNA8Z/ME4I6tKgQFFlljpbqeJumMTRdene4oaCq//rNmgeDbYqGR4ioiO";

  family:
    service-url: https://vg-ms-family-dcex.onrender.com

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/security-prs1
          # 🔥 OBLIGATORIO: URI de las claves públicas para verificar JWT
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG

  # Configuración de tiempo de espera
  datasource:
    initialization-mode: always
    initialization-timeout: 10s

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
