spring:
  application:
    name: vg-ms-info-test
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: 
  sql:
    init:
      mode: always
      timeout: 10s

server:
  port: 0  # Puerto aleatorio para tests

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG